Wetting is added in interImmersedBoundaryFoam. New class interfaceImmersedBoundaryProperties is added for immersed boundary wetting.

diff --git a/src/transportModels/Allwmake b/src/transportModels/Allwmake
--- a/src/transportModels/Allwmake
+++ b/src/transportModels/Allwmake
@@ -2,8 +2,8 @@
 cd ${0%/*} || exit 1    # run from this directory
 makeType=${1:-libso}
 
-wmakeCheckPwd "$WM_PROJECT_USER_DIR/src" || {
-    echo "Error: Current directory is not \$WM_PROJECT_USER_DIR/src"
+wmakeCheckPwd "$WM_PROJECT_USER_DIR/src/transportModels" || {
+    echo "Error: Current directory is not \$WM_PROJECT_USER_DIR/src/transportModels"
     echo "    The environment variables are inconsistent with the installation."
     echo "    Check the OpenFOAM entries in your dot-files and source them."
     exit 1
@@ -17,6 +17,7 @@ wmakeCheckPwd "$WM_PROJECT_USER_DIR/src" || {
 
 set -x
 
-lagrangian/Allwmake
-transportModels/Allwmake
+wmake $makeType interfaceImmersedBoundaryProperties
 
+
+# ----------------------------------------------------------------- end-of-file
